version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_erp
      TYPEORM_TYPE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
      TYPEORM_HOST: postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    

volumes:
  postgres_data:
